baseURL = "https://example.com"


# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "ja"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "千葉大学モダンジャズ研究会 - Chiba University Modern Jazz Society"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# enable emoji processing in Markdown (valid only for pure markdown content)
enableEmoji = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/cover-image.jpg"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "千葉大学モダンジャズ研究会 - Chiba University Modern Jazz Society"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Chiba University Modern Jazz Society"

    # Show a menu of languages available
    language_menu = false

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = false

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© 千葉大学モダンジャズ研究会"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = false

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false

    # Options used for automatic image generation. see: https://gohugo.io/content-management/image-processing/
    image_options = "webp q90 lanczos photo"

    # Use "page_title | site_title" for <title> tags
    # e.g. <title>Legal | 千葉大学モダンジャズ研究会 - Nutrition Coach & Chef Consultant</title>
    combine_page_and_site_title = false

    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = false

    [params.meta]
        keywords = "jazz, circle, Chiba, University"

    [[params.contacts]]
        label = "email"
        value = "chibajazz_hp@yahoo.co.jp"
        url = "mailto:chibajazz_hp@yahoo.co.jp"
        icon = "fa fa-envelope"

    [[params.contacts]]
        label = "instagram"
        value = "instagram"
        url = "https://instagram.com/chiba_jazz"
        icon = "fa-brands fa-instagram"

    [[params.contacts]]
        label = "x"
        value = "x"
        url = "https://x.com/Chiba_Jazz"
        icon = "fa-brands fa-x-twitter"

    [[params.contacts]]
        label = "youtube"
        value = "youtube"
        url = "https://youtube.com/@Chiba_Jazz"
        icon = "fa-brands fa-youtube"


    # Add additional contacts here!
    # [[params.contacts]]
    #     label = ""
    #     value = ""
    #     url = ""
    #     icon = ""

# Define additional languages
[languages]
  [languages.ja]
    weight = 1
    languageName = "Japanese"
    contentDir = "content/ja"

#   [languages.en]
#     weight = 10
#     languageName = "English"
#     contentDir = "content/en"

#   [languages.de]
#     title = "Erika Musterfrau - Ernährungshilfe & Kochberatung"
#     weight = 20
#     contentDir = "content/de"
#     languageName = "Deutsch"

# for GitHub Pages
# see: https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
  [caches.images]
    dir = ':cacheDir/images'